### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by ghost** [greeschenko/yii2-pay#1]
The requested package greeschenko/yii2-pay could not be found in any version, there may be a typo in the package name.

**Comment by greeschenko** [comment]
Hi, package under development and is not ready for publication in composer

currently working Paypal and Yandex (not tested) 

you can use plugin added to composer.json this code

`
 "repositories":[
        {
            "type": "git",
            "url": "https://github.com/greeschenko/yii2-pay"
        }
    ],
`
and this

`
    "require": {
         ....
        "greeschenko/yii2-pay": "dev-master"
         ....
    },
`
